/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsCreate } from "../funcs/tagsCreate.js";
import { tagsDelete } from "../funcs/tagsDelete.js";
import { tagsGet } from "../funcs/tagsGet.js";
import { tagsGetPopular } from "../funcs/tagsGetPopular.js";
import { tagsGetWithTickets } from "../funcs/tagsGetWithTickets.js";
import { tagsList } from "../funcs/tagsList.js";
import { tagsUpdate } from "../funcs/tagsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tags extends ClientSDK {
  async list(
    request: operations.ListTagsRequest,
    options?: RequestOptions,
  ): Promise<models.ApiResponseVecTagResponse> {
    return unwrapAsync(tagsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a tag
   *
   * @remarks
   * Requires permission: MANAGE_TAGS
   */
  async create(
    request: operations.CreateTagRequest,
    options?: RequestOptions,
  ): Promise<models.ApiResponseTagResponse> {
    return unwrapAsync(tagsCreate(
      this,
      request,
      options,
    ));
  }

  async getPopular(
    request: operations.GetPopularTagsRequest,
    options?: RequestOptions,
  ): Promise<models.ApiResponseVecTagResponse> {
    return unwrapAsync(tagsGetPopular(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.GetTagRequest,
    options?: RequestOptions,
  ): Promise<models.ApiResponseTagResponse> {
    return unwrapAsync(tagsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a tag
   *
   * @remarks
   * Requires permission: MANAGE_TAGS
   */
  async update(
    request: operations.UpdateTagRequest,
    options?: RequestOptions,
  ): Promise<models.ApiResponseTagResponse> {
    return unwrapAsync(tagsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a tag
   *
   * @remarks
   * Requires permission: MANAGE_TAGS
   */
  async delete(
    request: operations.DeleteTagRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(tagsDelete(
      this,
      request,
      options,
    ));
  }

  async getWithTickets(
    request: operations.GetTagWithTicketsRequest,
    options?: RequestOptions,
  ): Promise<models.ApiResponseTagWithTicketsResponse> {
    return unwrapAsync(tagsGetWithTickets(
      this,
      request,
      options,
    ));
  }
}
