/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateArticleRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  createArticleRequest: models.CreateArticleRequest;
};

/** @internal */
export const CreateArticleRequest$inboundSchema: z.ZodType<
  CreateArticleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  CreateArticleRequest: models.CreateArticleRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "CreateArticleRequest": "createArticleRequest",
  });
});

/** @internal */
export type CreateArticleRequest$Outbound = {
  org_id: string;
  CreateArticleRequest: models.CreateArticleRequest$Outbound;
};

/** @internal */
export const CreateArticleRequest$outboundSchema: z.ZodType<
  CreateArticleRequest$Outbound,
  z.ZodTypeDef,
  CreateArticleRequest
> = z.object({
  orgId: z.string(),
  createArticleRequest: models.CreateArticleRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    createArticleRequest: "CreateArticleRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateArticleRequest$ {
  /** @deprecated use `CreateArticleRequest$inboundSchema` instead. */
  export const inboundSchema = CreateArticleRequest$inboundSchema;
  /** @deprecated use `CreateArticleRequest$outboundSchema` instead. */
  export const outboundSchema = CreateArticleRequest$outboundSchema;
  /** @deprecated use `CreateArticleRequest$Outbound` instead. */
  export type Outbound = CreateArticleRequest$Outbound;
}

export function createArticleRequestToJSON(
  createArticleRequest: CreateArticleRequest,
): string {
  return JSON.stringify(
    CreateArticleRequest$outboundSchema.parse(createArticleRequest),
  );
}

export function createArticleRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateArticleRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateArticleRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateArticleRequest' from JSON`,
  );
}
