/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteMacroRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Macro ID
   */
  macroId: string;
};

/** @internal */
export const DeleteMacroRequest$inboundSchema: z.ZodType<
  DeleteMacroRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  macro_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "macro_id": "macroId",
  });
});

/** @internal */
export type DeleteMacroRequest$Outbound = {
  org_id: string;
  macro_id: string;
};

/** @internal */
export const DeleteMacroRequest$outboundSchema: z.ZodType<
  DeleteMacroRequest$Outbound,
  z.ZodTypeDef,
  DeleteMacroRequest
> = z.object({
  orgId: z.string(),
  macroId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    macroId: "macro_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteMacroRequest$ {
  /** @deprecated use `DeleteMacroRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteMacroRequest$inboundSchema;
  /** @deprecated use `DeleteMacroRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteMacroRequest$outboundSchema;
  /** @deprecated use `DeleteMacroRequest$Outbound` instead. */
  export type Outbound = DeleteMacroRequest$Outbound;
}

export function deleteMacroRequestToJSON(
  deleteMacroRequest: DeleteMacroRequest,
): string {
  return JSON.stringify(
    DeleteMacroRequest$outboundSchema.parse(deleteMacroRequest),
  );
}

export function deleteMacroRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteMacroRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteMacroRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteMacroRequest' from JSON`,
  );
}
