/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteOrganizationSettingRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Setting key
   */
  key: string;
};

/** @internal */
export const DeleteOrganizationSettingRequest$inboundSchema: z.ZodType<
  DeleteOrganizationSettingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  key: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
  });
});

/** @internal */
export type DeleteOrganizationSettingRequest$Outbound = {
  org_id: string;
  key: string;
};

/** @internal */
export const DeleteOrganizationSettingRequest$outboundSchema: z.ZodType<
  DeleteOrganizationSettingRequest$Outbound,
  z.ZodTypeDef,
  DeleteOrganizationSettingRequest
> = z.object({
  orgId: z.string(),
  key: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteOrganizationSettingRequest$ {
  /** @deprecated use `DeleteOrganizationSettingRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteOrganizationSettingRequest$inboundSchema;
  /** @deprecated use `DeleteOrganizationSettingRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteOrganizationSettingRequest$outboundSchema;
  /** @deprecated use `DeleteOrganizationSettingRequest$Outbound` instead. */
  export type Outbound = DeleteOrganizationSettingRequest$Outbound;
}

export function deleteOrganizationSettingRequestToJSON(
  deleteOrganizationSettingRequest: DeleteOrganizationSettingRequest,
): string {
  return JSON.stringify(
    DeleteOrganizationSettingRequest$outboundSchema.parse(
      deleteOrganizationSettingRequest,
    ),
  );
}

export function deleteOrganizationSettingRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteOrganizationSettingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteOrganizationSettingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteOrganizationSettingRequest' from JSON`,
  );
}
