/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteArticleRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Article ID
   */
  articleId: string;
};

/** @internal */
export const DeleteArticleRequest$inboundSchema: z.ZodType<
  DeleteArticleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  article_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "article_id": "articleId",
  });
});

/** @internal */
export type DeleteArticleRequest$Outbound = {
  org_id: string;
  article_id: string;
};

/** @internal */
export const DeleteArticleRequest$outboundSchema: z.ZodType<
  DeleteArticleRequest$Outbound,
  z.ZodTypeDef,
  DeleteArticleRequest
> = z.object({
  orgId: z.string(),
  articleId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    articleId: "article_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteArticleRequest$ {
  /** @deprecated use `DeleteArticleRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteArticleRequest$inboundSchema;
  /** @deprecated use `DeleteArticleRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteArticleRequest$outboundSchema;
  /** @deprecated use `DeleteArticleRequest$Outbound` instead. */
  export type Outbound = DeleteArticleRequest$Outbound;
}

export function deleteArticleRequestToJSON(
  deleteArticleRequest: DeleteArticleRequest,
): string {
  return JSON.stringify(
    DeleteArticleRequest$outboundSchema.parse(deleteArticleRequest),
  );
}

export function deleteArticleRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteArticleRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteArticleRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteArticleRequest' from JSON`,
  );
}
