/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetArticleRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Article ID
   */
  articleId: string;
};

/** @internal */
export const GetArticleRequest$inboundSchema: z.ZodType<
  GetArticleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  article_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "article_id": "articleId",
  });
});

/** @internal */
export type GetArticleRequest$Outbound = {
  org_id: string;
  article_id: string;
};

/** @internal */
export const GetArticleRequest$outboundSchema: z.ZodType<
  GetArticleRequest$Outbound,
  z.ZodTypeDef,
  GetArticleRequest
> = z.object({
  orgId: z.string(),
  articleId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    articleId: "article_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetArticleRequest$ {
  /** @deprecated use `GetArticleRequest$inboundSchema` instead. */
  export const inboundSchema = GetArticleRequest$inboundSchema;
  /** @deprecated use `GetArticleRequest$outboundSchema` instead. */
  export const outboundSchema = GetArticleRequest$outboundSchema;
  /** @deprecated use `GetArticleRequest$Outbound` instead. */
  export type Outbound = GetArticleRequest$Outbound;
}

export function getArticleRequestToJSON(
  getArticleRequest: GetArticleRequest,
): string {
  return JSON.stringify(
    GetArticleRequest$outboundSchema.parse(getArticleRequest),
  );
}

export function getArticleRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetArticleRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetArticleRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetArticleRequest' from JSON`,
  );
}
