/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAllOrganizationSettingsRequest = {
  /**
   * Organization ID
   */
  orgId: string;
};

/** @internal */
export const GetAllOrganizationSettingsRequest$inboundSchema: z.ZodType<
  GetAllOrganizationSettingsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
  });
});

/** @internal */
export type GetAllOrganizationSettingsRequest$Outbound = {
  org_id: string;
};

/** @internal */
export const GetAllOrganizationSettingsRequest$outboundSchema: z.ZodType<
  GetAllOrganizationSettingsRequest$Outbound,
  z.ZodTypeDef,
  GetAllOrganizationSettingsRequest
> = z.object({
  orgId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllOrganizationSettingsRequest$ {
  /** @deprecated use `GetAllOrganizationSettingsRequest$inboundSchema` instead. */
  export const inboundSchema = GetAllOrganizationSettingsRequest$inboundSchema;
  /** @deprecated use `GetAllOrganizationSettingsRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetAllOrganizationSettingsRequest$outboundSchema;
  /** @deprecated use `GetAllOrganizationSettingsRequest$Outbound` instead. */
  export type Outbound = GetAllOrganizationSettingsRequest$Outbound;
}

export function getAllOrganizationSettingsRequestToJSON(
  getAllOrganizationSettingsRequest: GetAllOrganizationSettingsRequest,
): string {
  return JSON.stringify(
    GetAllOrganizationSettingsRequest$outboundSchema.parse(
      getAllOrganizationSettingsRequest,
    ),
  );
}

export function getAllOrganizationSettingsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAllOrganizationSettingsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllOrganizationSettingsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllOrganizationSettingsRequest' from JSON`,
  );
}
