/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetKnowledgeBaseAnalyticsRequest = {
  /**
   * Organization ID
   */
  orgId: string;
};

/** @internal */
export const GetKnowledgeBaseAnalyticsRequest$inboundSchema: z.ZodType<
  GetKnowledgeBaseAnalyticsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
  });
});

/** @internal */
export type GetKnowledgeBaseAnalyticsRequest$Outbound = {
  org_id: string;
};

/** @internal */
export const GetKnowledgeBaseAnalyticsRequest$outboundSchema: z.ZodType<
  GetKnowledgeBaseAnalyticsRequest$Outbound,
  z.ZodTypeDef,
  GetKnowledgeBaseAnalyticsRequest
> = z.object({
  orgId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetKnowledgeBaseAnalyticsRequest$ {
  /** @deprecated use `GetKnowledgeBaseAnalyticsRequest$inboundSchema` instead. */
  export const inboundSchema = GetKnowledgeBaseAnalyticsRequest$inboundSchema;
  /** @deprecated use `GetKnowledgeBaseAnalyticsRequest$outboundSchema` instead. */
  export const outboundSchema = GetKnowledgeBaseAnalyticsRequest$outboundSchema;
  /** @deprecated use `GetKnowledgeBaseAnalyticsRequest$Outbound` instead. */
  export type Outbound = GetKnowledgeBaseAnalyticsRequest$Outbound;
}

export function getKnowledgeBaseAnalyticsRequestToJSON(
  getKnowledgeBaseAnalyticsRequest: GetKnowledgeBaseAnalyticsRequest,
): string {
  return JSON.stringify(
    GetKnowledgeBaseAnalyticsRequest$outboundSchema.parse(
      getKnowledgeBaseAnalyticsRequest,
    ),
  );
}

export function getKnowledgeBaseAnalyticsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetKnowledgeBaseAnalyticsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetKnowledgeBaseAnalyticsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetKnowledgeBaseAnalyticsRequest' from JSON`,
  );
}
