/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetMacroRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Macro ID
   */
  macroId: string;
};

/** @internal */
export const GetMacroRequest$inboundSchema: z.ZodType<
  GetMacroRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  macro_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "macro_id": "macroId",
  });
});

/** @internal */
export type GetMacroRequest$Outbound = {
  org_id: string;
  macro_id: string;
};

/** @internal */
export const GetMacroRequest$outboundSchema: z.ZodType<
  GetMacroRequest$Outbound,
  z.ZodTypeDef,
  GetMacroRequest
> = z.object({
  orgId: z.string(),
  macroId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    macroId: "macro_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMacroRequest$ {
  /** @deprecated use `GetMacroRequest$inboundSchema` instead. */
  export const inboundSchema = GetMacroRequest$inboundSchema;
  /** @deprecated use `GetMacroRequest$outboundSchema` instead. */
  export const outboundSchema = GetMacroRequest$outboundSchema;
  /** @deprecated use `GetMacroRequest$Outbound` instead. */
  export type Outbound = GetMacroRequest$Outbound;
}

export function getMacroRequestToJSON(
  getMacroRequest: GetMacroRequest,
): string {
  return JSON.stringify(GetMacroRequest$outboundSchema.parse(getMacroRequest));
}

export function getMacroRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetMacroRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMacroRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMacroRequest' from JSON`,
  );
}
