/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetMacroAnalyticsRequest = {
  /**
   * Organization ID
   */
  orgId: string;
};

/** @internal */
export const GetMacroAnalyticsRequest$inboundSchema: z.ZodType<
  GetMacroAnalyticsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
  });
});

/** @internal */
export type GetMacroAnalyticsRequest$Outbound = {
  org_id: string;
};

/** @internal */
export const GetMacroAnalyticsRequest$outboundSchema: z.ZodType<
  GetMacroAnalyticsRequest$Outbound,
  z.ZodTypeDef,
  GetMacroAnalyticsRequest
> = z.object({
  orgId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMacroAnalyticsRequest$ {
  /** @deprecated use `GetMacroAnalyticsRequest$inboundSchema` instead. */
  export const inboundSchema = GetMacroAnalyticsRequest$inboundSchema;
  /** @deprecated use `GetMacroAnalyticsRequest$outboundSchema` instead. */
  export const outboundSchema = GetMacroAnalyticsRequest$outboundSchema;
  /** @deprecated use `GetMacroAnalyticsRequest$Outbound` instead. */
  export type Outbound = GetMacroAnalyticsRequest$Outbound;
}

export function getMacroAnalyticsRequestToJSON(
  getMacroAnalyticsRequest: GetMacroAnalyticsRequest,
): string {
  return JSON.stringify(
    GetMacroAnalyticsRequest$outboundSchema.parse(getMacroAnalyticsRequest),
  );
}

export function getMacroAnalyticsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetMacroAnalyticsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMacroAnalyticsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMacroAnalyticsRequest' from JSON`,
  );
}
