/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPublicArticlesRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  perPage?: number | undefined;
};

/** @internal */
export const GetPublicArticlesRequest$inboundSchema: z.ZodType<
  GetPublicArticlesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  page: z.number().int().optional(),
  per_page: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "per_page": "perPage",
  });
});

/** @internal */
export type GetPublicArticlesRequest$Outbound = {
  org_id: string;
  page?: number | undefined;
  per_page?: number | undefined;
};

/** @internal */
export const GetPublicArticlesRequest$outboundSchema: z.ZodType<
  GetPublicArticlesRequest$Outbound,
  z.ZodTypeDef,
  GetPublicArticlesRequest
> = z.object({
  orgId: z.string(),
  page: z.number().int().optional(),
  perPage: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    perPage: "per_page",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPublicArticlesRequest$ {
  /** @deprecated use `GetPublicArticlesRequest$inboundSchema` instead. */
  export const inboundSchema = GetPublicArticlesRequest$inboundSchema;
  /** @deprecated use `GetPublicArticlesRequest$outboundSchema` instead. */
  export const outboundSchema = GetPublicArticlesRequest$outboundSchema;
  /** @deprecated use `GetPublicArticlesRequest$Outbound` instead. */
  export type Outbound = GetPublicArticlesRequest$Outbound;
}

export function getPublicArticlesRequestToJSON(
  getPublicArticlesRequest: GetPublicArticlesRequest,
): string {
  return JSON.stringify(
    GetPublicArticlesRequest$outboundSchema.parse(getPublicArticlesRequest),
  );
}

export function getPublicArticlesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPublicArticlesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPublicArticlesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublicArticlesRequest' from JSON`,
  );
}
