/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPopularTagsRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Maximum number of tags to return
   */
  limit?: number | undefined;
};

/** @internal */
export const GetPopularTagsRequest$inboundSchema: z.ZodType<
  GetPopularTagsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  limit: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
  });
});

/** @internal */
export type GetPopularTagsRequest$Outbound = {
  org_id: string;
  limit?: number | undefined;
};

/** @internal */
export const GetPopularTagsRequest$outboundSchema: z.ZodType<
  GetPopularTagsRequest$Outbound,
  z.ZodTypeDef,
  GetPopularTagsRequest
> = z.object({
  orgId: z.string(),
  limit: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPopularTagsRequest$ {
  /** @deprecated use `GetPopularTagsRequest$inboundSchema` instead. */
  export const inboundSchema = GetPopularTagsRequest$inboundSchema;
  /** @deprecated use `GetPopularTagsRequest$outboundSchema` instead. */
  export const outboundSchema = GetPopularTagsRequest$outboundSchema;
  /** @deprecated use `GetPopularTagsRequest$Outbound` instead. */
  export type Outbound = GetPopularTagsRequest$Outbound;
}

export function getPopularTagsRequestToJSON(
  getPopularTagsRequest: GetPopularTagsRequest,
): string {
  return JSON.stringify(
    GetPopularTagsRequest$outboundSchema.parse(getPopularTagsRequest),
  );
}

export function getPopularTagsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPopularTagsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPopularTagsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPopularTagsRequest' from JSON`,
  );
}
