/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetRoleRequest = {
  orgId: string;
  roleId: string;
};

/** @internal */
export const GetRoleRequest$inboundSchema: z.ZodType<
  GetRoleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  role_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "role_id": "roleId",
  });
});

/** @internal */
export type GetRoleRequest$Outbound = {
  org_id: string;
  role_id: string;
};

/** @internal */
export const GetRoleRequest$outboundSchema: z.ZodType<
  GetRoleRequest$Outbound,
  z.ZodTypeDef,
  GetRoleRequest
> = z.object({
  orgId: z.string(),
  roleId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    roleId: "role_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRoleRequest$ {
  /** @deprecated use `GetRoleRequest$inboundSchema` instead. */
  export const inboundSchema = GetRoleRequest$inboundSchema;
  /** @deprecated use `GetRoleRequest$outboundSchema` instead. */
  export const outboundSchema = GetRoleRequest$outboundSchema;
  /** @deprecated use `GetRoleRequest$Outbound` instead. */
  export type Outbound = GetRoleRequest$Outbound;
}

export function getRoleRequestToJSON(getRoleRequest: GetRoleRequest): string {
  return JSON.stringify(GetRoleRequest$outboundSchema.parse(getRoleRequest));
}

export function getRoleRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRoleRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRoleRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRoleRequest' from JSON`,
  );
}
