/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSurveyAnalyticsRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Start date for analytics (ISO 8601)
   */
  fromDate?: string | undefined;
  /**
   * End date for analytics (ISO 8601)
   */
  toDate?: string | undefined;
};

/** @internal */
export const GetSurveyAnalyticsRequest$inboundSchema: z.ZodType<
  GetSurveyAnalyticsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  from_date: z.string().optional(),
  to_date: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "from_date": "fromDate",
    "to_date": "toDate",
  });
});

/** @internal */
export type GetSurveyAnalyticsRequest$Outbound = {
  org_id: string;
  from_date?: string | undefined;
  to_date?: string | undefined;
};

/** @internal */
export const GetSurveyAnalyticsRequest$outboundSchema: z.ZodType<
  GetSurveyAnalyticsRequest$Outbound,
  z.ZodTypeDef,
  GetSurveyAnalyticsRequest
> = z.object({
  orgId: z.string(),
  fromDate: z.string().optional(),
  toDate: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    fromDate: "from_date",
    toDate: "to_date",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSurveyAnalyticsRequest$ {
  /** @deprecated use `GetSurveyAnalyticsRequest$inboundSchema` instead. */
  export const inboundSchema = GetSurveyAnalyticsRequest$inboundSchema;
  /** @deprecated use `GetSurveyAnalyticsRequest$outboundSchema` instead. */
  export const outboundSchema = GetSurveyAnalyticsRequest$outboundSchema;
  /** @deprecated use `GetSurveyAnalyticsRequest$Outbound` instead. */
  export type Outbound = GetSurveyAnalyticsRequest$Outbound;
}

export function getSurveyAnalyticsRequestToJSON(
  getSurveyAnalyticsRequest: GetSurveyAnalyticsRequest,
): string {
  return JSON.stringify(
    GetSurveyAnalyticsRequest$outboundSchema.parse(getSurveyAnalyticsRequest),
  );
}

export function getSurveyAnalyticsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSurveyAnalyticsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSurveyAnalyticsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSurveyAnalyticsRequest' from JSON`,
  );
}
