/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSystemAnalyticsRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Start date for analytics (ISO 8601)
   */
  fromDate?: string | undefined;
  /**
   * End date for analytics (ISO 8601)
   */
  toDate?: string | undefined;
};

/** @internal */
export const GetSystemAnalyticsRequest$inboundSchema: z.ZodType<
  GetSystemAnalyticsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  from_date: z.string().optional(),
  to_date: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "from_date": "fromDate",
    "to_date": "toDate",
  });
});

/** @internal */
export type GetSystemAnalyticsRequest$Outbound = {
  org_id: string;
  from_date?: string | undefined;
  to_date?: string | undefined;
};

/** @internal */
export const GetSystemAnalyticsRequest$outboundSchema: z.ZodType<
  GetSystemAnalyticsRequest$Outbound,
  z.ZodTypeDef,
  GetSystemAnalyticsRequest
> = z.object({
  orgId: z.string(),
  fromDate: z.string().optional(),
  toDate: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    fromDate: "from_date",
    toDate: "to_date",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSystemAnalyticsRequest$ {
  /** @deprecated use `GetSystemAnalyticsRequest$inboundSchema` instead. */
  export const inboundSchema = GetSystemAnalyticsRequest$inboundSchema;
  /** @deprecated use `GetSystemAnalyticsRequest$outboundSchema` instead. */
  export const outboundSchema = GetSystemAnalyticsRequest$outboundSchema;
  /** @deprecated use `GetSystemAnalyticsRequest$Outbound` instead. */
  export type Outbound = GetSystemAnalyticsRequest$Outbound;
}

export function getSystemAnalyticsRequestToJSON(
  getSystemAnalyticsRequest: GetSystemAnalyticsRequest,
): string {
  return JSON.stringify(
    GetSystemAnalyticsRequest$outboundSchema.parse(getSystemAnalyticsRequest),
  );
}

export function getSystemAnalyticsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSystemAnalyticsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSystemAnalyticsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSystemAnalyticsRequest' from JSON`,
  );
}
