/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListArticlesRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Filter by public visibility
   */
  public?: boolean | undefined;
  /**
   * Filter by author user ID
   */
  authorId?: string | undefined;
  /**
   * Search in title and content
   */
  search?: string | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  perPage?: number | undefined;
};

/** @internal */
export const ListArticlesRequest$inboundSchema: z.ZodType<
  ListArticlesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  public: z.boolean().optional(),
  author_id: z.string().optional(),
  search: z.string().optional(),
  page: z.number().int().optional(),
  per_page: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "author_id": "authorId",
    "per_page": "perPage",
  });
});

/** @internal */
export type ListArticlesRequest$Outbound = {
  org_id: string;
  public?: boolean | undefined;
  author_id?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  per_page?: number | undefined;
};

/** @internal */
export const ListArticlesRequest$outboundSchema: z.ZodType<
  ListArticlesRequest$Outbound,
  z.ZodTypeDef,
  ListArticlesRequest
> = z.object({
  orgId: z.string(),
  public: z.boolean().optional(),
  authorId: z.string().optional(),
  search: z.string().optional(),
  page: z.number().int().optional(),
  perPage: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    authorId: "author_id",
    perPage: "per_page",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListArticlesRequest$ {
  /** @deprecated use `ListArticlesRequest$inboundSchema` instead. */
  export const inboundSchema = ListArticlesRequest$inboundSchema;
  /** @deprecated use `ListArticlesRequest$outboundSchema` instead. */
  export const outboundSchema = ListArticlesRequest$outboundSchema;
  /** @deprecated use `ListArticlesRequest$Outbound` instead. */
  export type Outbound = ListArticlesRequest$Outbound;
}

export function listArticlesRequestToJSON(
  listArticlesRequest: ListArticlesRequest,
): string {
  return JSON.stringify(
    ListArticlesRequest$outboundSchema.parse(listArticlesRequest),
  );
}

export function listArticlesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListArticlesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListArticlesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListArticlesRequest' from JSON`,
  );
}
