/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListWebhookEventsRequest = {
  /**
   * Organization ID
   */
  orgId: string;
};

/** @internal */
export const ListWebhookEventsRequest$inboundSchema: z.ZodType<
  ListWebhookEventsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
  });
});

/** @internal */
export type ListWebhookEventsRequest$Outbound = {
  org_id: string;
};

/** @internal */
export const ListWebhookEventsRequest$outboundSchema: z.ZodType<
  ListWebhookEventsRequest$Outbound,
  z.ZodTypeDef,
  ListWebhookEventsRequest
> = z.object({
  orgId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListWebhookEventsRequest$ {
  /** @deprecated use `ListWebhookEventsRequest$inboundSchema` instead. */
  export const inboundSchema = ListWebhookEventsRequest$inboundSchema;
  /** @deprecated use `ListWebhookEventsRequest$outboundSchema` instead. */
  export const outboundSchema = ListWebhookEventsRequest$outboundSchema;
  /** @deprecated use `ListWebhookEventsRequest$Outbound` instead. */
  export type Outbound = ListWebhookEventsRequest$Outbound;
}

export function listWebhookEventsRequestToJSON(
  listWebhookEventsRequest: ListWebhookEventsRequest,
): string {
  return JSON.stringify(
    ListWebhookEventsRequest$outboundSchema.parse(listWebhookEventsRequest),
  );
}

export function listWebhookEventsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListWebhookEventsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWebhookEventsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWebhookEventsRequest' from JSON`,
  );
}
