/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveMemberRequest = {
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Member user ID
   */
  memberId: string;
};

/** @internal */
export const RemoveMemberRequest$inboundSchema: z.ZodType<
  RemoveMemberRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org_id: z.string(),
  member_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "member_id": "memberId",
  });
});

/** @internal */
export type RemoveMemberRequest$Outbound = {
  org_id: string;
  member_id: string;
};

/** @internal */
export const RemoveMemberRequest$outboundSchema: z.ZodType<
  RemoveMemberRequest$Outbound,
  z.ZodTypeDef,
  RemoveMemberRequest
> = z.object({
  orgId: z.string(),
  memberId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orgId: "org_id",
    memberId: "member_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RemoveMemberRequest$ {
  /** @deprecated use `RemoveMemberRequest$inboundSchema` instead. */
  export const inboundSchema = RemoveMemberRequest$inboundSchema;
  /** @deprecated use `RemoveMemberRequest$outboundSchema` instead. */
  export const outboundSchema = RemoveMemberRequest$outboundSchema;
  /** @deprecated use `RemoveMemberRequest$Outbound` instead. */
  export type Outbound = RemoveMemberRequest$Outbound;
}

export function removeMemberRequestToJSON(
  removeMemberRequest: RemoveMemberRequest,
): string {
  return JSON.stringify(
    RemoveMemberRequest$outboundSchema.parse(removeMemberRequest),
  );
}

export function removeMemberRequestFromJSON(
  jsonString: string,
): SafeParseResult<RemoveMemberRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveMemberRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveMemberRequest' from JSON`,
  );
}
