/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiResponseWebhookResponseData = {
  createdAt: string;
  description?: string | null | undefined;
  enabled: boolean;
  events: Array<string>;
  failureCount: number;
  headers?: { [k: string]: string } | null | undefined;
  id: string;
  lastDelivery?: string | null | undefined;
  name: string;
  organizationId: string;
  successCount: number;
  updatedAt: string;
  url: string;
};

export type ApiResponseWebhookResponse = {
  data?: ApiResponseWebhookResponseData | undefined;
  message?: string | null | undefined;
  success: boolean;
};

/** @internal */
export const ApiResponseWebhookResponseData$inboundSchema: z.ZodType<
  ApiResponseWebhookResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string(),
  description: z.nullable(z.string()).optional(),
  enabled: z.boolean(),
  events: z.array(z.string()),
  failure_count: z.number().int(),
  headers: z.nullable(z.record(z.string())).optional(),
  id: z.string(),
  last_delivery: z.nullable(z.string()).optional(),
  name: z.string(),
  organization_id: z.string(),
  success_count: z.number().int(),
  updated_at: z.string(),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "failure_count": "failureCount",
    "last_delivery": "lastDelivery",
    "organization_id": "organizationId",
    "success_count": "successCount",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type ApiResponseWebhookResponseData$Outbound = {
  created_at: string;
  description?: string | null | undefined;
  enabled: boolean;
  events: Array<string>;
  failure_count: number;
  headers?: { [k: string]: string } | null | undefined;
  id: string;
  last_delivery?: string | null | undefined;
  name: string;
  organization_id: string;
  success_count: number;
  updated_at: string;
  url: string;
};

/** @internal */
export const ApiResponseWebhookResponseData$outboundSchema: z.ZodType<
  ApiResponseWebhookResponseData$Outbound,
  z.ZodTypeDef,
  ApiResponseWebhookResponseData
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()).optional(),
  enabled: z.boolean(),
  events: z.array(z.string()),
  failureCount: z.number().int(),
  headers: z.nullable(z.record(z.string())).optional(),
  id: z.string(),
  lastDelivery: z.nullable(z.string()).optional(),
  name: z.string(),
  organizationId: z.string(),
  successCount: z.number().int(),
  updatedAt: z.string(),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    failureCount: "failure_count",
    lastDelivery: "last_delivery",
    organizationId: "organization_id",
    successCount: "success_count",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiResponseWebhookResponseData$ {
  /** @deprecated use `ApiResponseWebhookResponseData$inboundSchema` instead. */
  export const inboundSchema = ApiResponseWebhookResponseData$inboundSchema;
  /** @deprecated use `ApiResponseWebhookResponseData$outboundSchema` instead. */
  export const outboundSchema = ApiResponseWebhookResponseData$outboundSchema;
  /** @deprecated use `ApiResponseWebhookResponseData$Outbound` instead. */
  export type Outbound = ApiResponseWebhookResponseData$Outbound;
}

export function apiResponseWebhookResponseDataToJSON(
  apiResponseWebhookResponseData: ApiResponseWebhookResponseData,
): string {
  return JSON.stringify(
    ApiResponseWebhookResponseData$outboundSchema.parse(
      apiResponseWebhookResponseData,
    ),
  );
}

export function apiResponseWebhookResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiResponseWebhookResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiResponseWebhookResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiResponseWebhookResponseData' from JSON`,
  );
}

/** @internal */
export const ApiResponseWebhookResponse$inboundSchema: z.ZodType<
  ApiResponseWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ApiResponseWebhookResponseData$inboundSchema).optional(),
  message: z.nullable(z.string()).optional(),
  success: z.boolean(),
});

/** @internal */
export type ApiResponseWebhookResponse$Outbound = {
  data?: ApiResponseWebhookResponseData$Outbound | undefined;
  message?: string | null | undefined;
  success: boolean;
};

/** @internal */
export const ApiResponseWebhookResponse$outboundSchema: z.ZodType<
  ApiResponseWebhookResponse$Outbound,
  z.ZodTypeDef,
  ApiResponseWebhookResponse
> = z.object({
  data: z.lazy(() => ApiResponseWebhookResponseData$outboundSchema).optional(),
  message: z.nullable(z.string()).optional(),
  success: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiResponseWebhookResponse$ {
  /** @deprecated use `ApiResponseWebhookResponse$inboundSchema` instead. */
  export const inboundSchema = ApiResponseWebhookResponse$inboundSchema;
  /** @deprecated use `ApiResponseWebhookResponse$outboundSchema` instead. */
  export const outboundSchema = ApiResponseWebhookResponse$outboundSchema;
  /** @deprecated use `ApiResponseWebhookResponse$Outbound` instead. */
  export type Outbound = ApiResponseWebhookResponse$Outbound;
}

export function apiResponseWebhookResponseToJSON(
  apiResponseWebhookResponse: ApiResponseWebhookResponse,
): string {
  return JSON.stringify(
    ApiResponseWebhookResponse$outboundSchema.parse(apiResponseWebhookResponse),
  );
}

export function apiResponseWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiResponseWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiResponseWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiResponseWebhookResponse' from JSON`,
  );
}
