/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiResponseSystemUsageData = {
  activeSessions: number;
  apiCallsToday: number;
  peakDayOfWeek: string;
  peakHour: number;
  totalEventsThisMonth: number;
  totalEventsThisWeek: number;
  totalEventsToday: number;
};

export type ApiResponseSystemUsage = {
  data?: ApiResponseSystemUsageData | undefined;
  message?: string | null | undefined;
  success: boolean;
};

/** @internal */
export const ApiResponseSystemUsageData$inboundSchema: z.ZodType<
  ApiResponseSystemUsageData,
  z.ZodTypeDef,
  unknown
> = z.object({
  active_sessions: z.number().int(),
  api_calls_today: z.number().int(),
  peak_day_of_week: z.string(),
  peak_hour: z.number().int(),
  total_events_this_month: z.number().int(),
  total_events_this_week: z.number().int(),
  total_events_today: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "active_sessions": "activeSessions",
    "api_calls_today": "apiCallsToday",
    "peak_day_of_week": "peakDayOfWeek",
    "peak_hour": "peakHour",
    "total_events_this_month": "totalEventsThisMonth",
    "total_events_this_week": "totalEventsThisWeek",
    "total_events_today": "totalEventsToday",
  });
});

/** @internal */
export type ApiResponseSystemUsageData$Outbound = {
  active_sessions: number;
  api_calls_today: number;
  peak_day_of_week: string;
  peak_hour: number;
  total_events_this_month: number;
  total_events_this_week: number;
  total_events_today: number;
};

/** @internal */
export const ApiResponseSystemUsageData$outboundSchema: z.ZodType<
  ApiResponseSystemUsageData$Outbound,
  z.ZodTypeDef,
  ApiResponseSystemUsageData
> = z.object({
  activeSessions: z.number().int(),
  apiCallsToday: z.number().int(),
  peakDayOfWeek: z.string(),
  peakHour: z.number().int(),
  totalEventsThisMonth: z.number().int(),
  totalEventsThisWeek: z.number().int(),
  totalEventsToday: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    activeSessions: "active_sessions",
    apiCallsToday: "api_calls_today",
    peakDayOfWeek: "peak_day_of_week",
    peakHour: "peak_hour",
    totalEventsThisMonth: "total_events_this_month",
    totalEventsThisWeek: "total_events_this_week",
    totalEventsToday: "total_events_today",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiResponseSystemUsageData$ {
  /** @deprecated use `ApiResponseSystemUsageData$inboundSchema` instead. */
  export const inboundSchema = ApiResponseSystemUsageData$inboundSchema;
  /** @deprecated use `ApiResponseSystemUsageData$outboundSchema` instead. */
  export const outboundSchema = ApiResponseSystemUsageData$outboundSchema;
  /** @deprecated use `ApiResponseSystemUsageData$Outbound` instead. */
  export type Outbound = ApiResponseSystemUsageData$Outbound;
}

export function apiResponseSystemUsageDataToJSON(
  apiResponseSystemUsageData: ApiResponseSystemUsageData,
): string {
  return JSON.stringify(
    ApiResponseSystemUsageData$outboundSchema.parse(apiResponseSystemUsageData),
  );
}

export function apiResponseSystemUsageDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiResponseSystemUsageData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiResponseSystemUsageData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiResponseSystemUsageData' from JSON`,
  );
}

/** @internal */
export const ApiResponseSystemUsage$inboundSchema: z.ZodType<
  ApiResponseSystemUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ApiResponseSystemUsageData$inboundSchema).optional(),
  message: z.nullable(z.string()).optional(),
  success: z.boolean(),
});

/** @internal */
export type ApiResponseSystemUsage$Outbound = {
  data?: ApiResponseSystemUsageData$Outbound | undefined;
  message?: string | null | undefined;
  success: boolean;
};

/** @internal */
export const ApiResponseSystemUsage$outboundSchema: z.ZodType<
  ApiResponseSystemUsage$Outbound,
  z.ZodTypeDef,
  ApiResponseSystemUsage
> = z.object({
  data: z.lazy(() => ApiResponseSystemUsageData$outboundSchema).optional(),
  message: z.nullable(z.string()).optional(),
  success: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiResponseSystemUsage$ {
  /** @deprecated use `ApiResponseSystemUsage$inboundSchema` instead. */
  export const inboundSchema = ApiResponseSystemUsage$inboundSchema;
  /** @deprecated use `ApiResponseSystemUsage$outboundSchema` instead. */
  export const outboundSchema = ApiResponseSystemUsage$outboundSchema;
  /** @deprecated use `ApiResponseSystemUsage$Outbound` instead. */
  export type Outbound = ApiResponseSystemUsage$Outbound;
}

export function apiResponseSystemUsageToJSON(
  apiResponseSystemUsage: ApiResponseSystemUsage,
): string {
  return JSON.stringify(
    ApiResponseSystemUsage$outboundSchema.parse(apiResponseSystemUsage),
  );
}

export function apiResponseSystemUsageFromJSON(
  jsonString: string,
): SafeParseResult<ApiResponseSystemUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiResponseSystemUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiResponseSystemUsage' from JSON`,
  );
}
