/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ApiResponseEffectivePermissionsResponseData = {
  effectivePermissions: number;
};

export type ApiResponseEffectivePermissionsResponse = {
  data?: ApiResponseEffectivePermissionsResponseData | undefined;
  message?: string | null | undefined;
  success: boolean;
};

/** @internal */
export const ApiResponseEffectivePermissionsResponseData$inboundSchema:
  z.ZodType<
    ApiResponseEffectivePermissionsResponseData,
    z.ZodTypeDef,
    unknown
  > = z.object({
    effective_permissions: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "effective_permissions": "effectivePermissions",
    });
  });

/** @internal */
export type ApiResponseEffectivePermissionsResponseData$Outbound = {
  effective_permissions: number;
};

/** @internal */
export const ApiResponseEffectivePermissionsResponseData$outboundSchema:
  z.ZodType<
    ApiResponseEffectivePermissionsResponseData$Outbound,
    z.ZodTypeDef,
    ApiResponseEffectivePermissionsResponseData
  > = z.object({
    effectivePermissions: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      effectivePermissions: "effective_permissions",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiResponseEffectivePermissionsResponseData$ {
  /** @deprecated use `ApiResponseEffectivePermissionsResponseData$inboundSchema` instead. */
  export const inboundSchema =
    ApiResponseEffectivePermissionsResponseData$inboundSchema;
  /** @deprecated use `ApiResponseEffectivePermissionsResponseData$outboundSchema` instead. */
  export const outboundSchema =
    ApiResponseEffectivePermissionsResponseData$outboundSchema;
  /** @deprecated use `ApiResponseEffectivePermissionsResponseData$Outbound` instead. */
  export type Outbound = ApiResponseEffectivePermissionsResponseData$Outbound;
}

export function apiResponseEffectivePermissionsResponseDataToJSON(
  apiResponseEffectivePermissionsResponseData:
    ApiResponseEffectivePermissionsResponseData,
): string {
  return JSON.stringify(
    ApiResponseEffectivePermissionsResponseData$outboundSchema.parse(
      apiResponseEffectivePermissionsResponseData,
    ),
  );
}

export function apiResponseEffectivePermissionsResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiResponseEffectivePermissionsResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiResponseEffectivePermissionsResponseData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiResponseEffectivePermissionsResponseData' from JSON`,
  );
}

/** @internal */
export const ApiResponseEffectivePermissionsResponse$inboundSchema: z.ZodType<
  ApiResponseEffectivePermissionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ApiResponseEffectivePermissionsResponseData$inboundSchema)
    .optional(),
  message: z.nullable(z.string()).optional(),
  success: z.boolean(),
});

/** @internal */
export type ApiResponseEffectivePermissionsResponse$Outbound = {
  data?: ApiResponseEffectivePermissionsResponseData$Outbound | undefined;
  message?: string | null | undefined;
  success: boolean;
};

/** @internal */
export const ApiResponseEffectivePermissionsResponse$outboundSchema: z.ZodType<
  ApiResponseEffectivePermissionsResponse$Outbound,
  z.ZodTypeDef,
  ApiResponseEffectivePermissionsResponse
> = z.object({
  data: z.lazy(() => ApiResponseEffectivePermissionsResponseData$outboundSchema)
    .optional(),
  message: z.nullable(z.string()).optional(),
  success: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiResponseEffectivePermissionsResponse$ {
  /** @deprecated use `ApiResponseEffectivePermissionsResponse$inboundSchema` instead. */
  export const inboundSchema =
    ApiResponseEffectivePermissionsResponse$inboundSchema;
  /** @deprecated use `ApiResponseEffectivePermissionsResponse$outboundSchema` instead. */
  export const outboundSchema =
    ApiResponseEffectivePermissionsResponse$outboundSchema;
  /** @deprecated use `ApiResponseEffectivePermissionsResponse$Outbound` instead. */
  export type Outbound = ApiResponseEffectivePermissionsResponse$Outbound;
}

export function apiResponseEffectivePermissionsResponseToJSON(
  apiResponseEffectivePermissionsResponse:
    ApiResponseEffectivePermissionsResponse,
): string {
  return JSON.stringify(
    ApiResponseEffectivePermissionsResponse$outboundSchema.parse(
      apiResponseEffectivePermissionsResponse,
    ),
  );
}

export function apiResponseEffectivePermissionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiResponseEffectivePermissionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiResponseEffectivePermissionsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiResponseEffectivePermissionsResponse' from JSON`,
  );
}
