/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreateApiKeyRequest = {
  expiresInDays?: number | null | undefined;
  name: string;
  scopes: Array<string>;
};

/** @internal */
export const CreateApiKeyRequest$inboundSchema: z.ZodType<
  CreateApiKeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  expires_in_days: z.nullable(z.number().int()).optional(),
  name: z.string(),
  scopes: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "expires_in_days": "expiresInDays",
  });
});

/** @internal */
export type CreateApiKeyRequest$Outbound = {
  expires_in_days?: number | null | undefined;
  name: string;
  scopes: Array<string>;
};

/** @internal */
export const CreateApiKeyRequest$outboundSchema: z.ZodType<
  CreateApiKeyRequest$Outbound,
  z.ZodTypeDef,
  CreateApiKeyRequest
> = z.object({
  expiresInDays: z.nullable(z.number().int()).optional(),
  name: z.string(),
  scopes: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    expiresInDays: "expires_in_days",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateApiKeyRequest$ {
  /** @deprecated use `CreateApiKeyRequest$inboundSchema` instead. */
  export const inboundSchema = CreateApiKeyRequest$inboundSchema;
  /** @deprecated use `CreateApiKeyRequest$outboundSchema` instead. */
  export const outboundSchema = CreateApiKeyRequest$outboundSchema;
  /** @deprecated use `CreateApiKeyRequest$Outbound` instead. */
  export type Outbound = CreateApiKeyRequest$Outbound;
}

export function createApiKeyRequestToJSON(
  createApiKeyRequest: CreateApiKeyRequest,
): string {
  return JSON.stringify(
    CreateApiKeyRequest$outboundSchema.parse(createApiKeyRequest),
  );
}

export function createApiKeyRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKeyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKeyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKeyRequest' from JSON`,
  );
}
