/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ResendVerificationRequest = {
  email: string;
};

/** @internal */
export const ResendVerificationRequest$inboundSchema: z.ZodType<
  ResendVerificationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
});

/** @internal */
export type ResendVerificationRequest$Outbound = {
  email: string;
};

/** @internal */
export const ResendVerificationRequest$outboundSchema: z.ZodType<
  ResendVerificationRequest$Outbound,
  z.ZodTypeDef,
  ResendVerificationRequest
> = z.object({
  email: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResendVerificationRequest$ {
  /** @deprecated use `ResendVerificationRequest$inboundSchema` instead. */
  export const inboundSchema = ResendVerificationRequest$inboundSchema;
  /** @deprecated use `ResendVerificationRequest$outboundSchema` instead. */
  export const outboundSchema = ResendVerificationRequest$outboundSchema;
  /** @deprecated use `ResendVerificationRequest$Outbound` instead. */
  export type Outbound = ResendVerificationRequest$Outbound;
}

export function resendVerificationRequestToJSON(
  resendVerificationRequest: ResendVerificationRequest,
): string {
  return JSON.stringify(
    ResendVerificationRequest$outboundSchema.parse(resendVerificationRequest),
  );
}

export function resendVerificationRequestFromJSON(
  jsonString: string,
): SafeParseResult<ResendVerificationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResendVerificationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResendVerificationRequest' from JSON`,
  );
}
