/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ScoreCount = {
  count: number;
  percentage: number;
  score: number;
};

/** @internal */
export const ScoreCount$inboundSchema: z.ZodType<
  ScoreCount,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().int(),
  percentage: z.number(),
  score: z.number().int(),
});

/** @internal */
export type ScoreCount$Outbound = {
  count: number;
  percentage: number;
  score: number;
};

/** @internal */
export const ScoreCount$outboundSchema: z.ZodType<
  ScoreCount$Outbound,
  z.ZodTypeDef,
  ScoreCount
> = z.object({
  count: z.number().int(),
  percentage: z.number(),
  score: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ScoreCount$ {
  /** @deprecated use `ScoreCount$inboundSchema` instead. */
  export const inboundSchema = ScoreCount$inboundSchema;
  /** @deprecated use `ScoreCount$outboundSchema` instead. */
  export const outboundSchema = ScoreCount$outboundSchema;
  /** @deprecated use `ScoreCount$Outbound` instead. */
  export type Outbound = ScoreCount$Outbound;
}

export function scoreCountToJSON(scoreCount: ScoreCount): string {
  return JSON.stringify(ScoreCount$outboundSchema.parse(scoreCount));
}

export function scoreCountFromJSON(
  jsonString: string,
): SafeParseResult<ScoreCount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScoreCount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScoreCount' from JSON`,
  );
}
