/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TagManagementRequest = {
  tagIds: Array<string>;
};

/** @internal */
export const TagManagementRequest$inboundSchema: z.ZodType<
  TagManagementRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  tag_ids: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "tag_ids": "tagIds",
  });
});

/** @internal */
export type TagManagementRequest$Outbound = {
  tag_ids: Array<string>;
};

/** @internal */
export const TagManagementRequest$outboundSchema: z.ZodType<
  TagManagementRequest$Outbound,
  z.ZodTypeDef,
  TagManagementRequest
> = z.object({
  tagIds: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    tagIds: "tag_ids",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TagManagementRequest$ {
  /** @deprecated use `TagManagementRequest$inboundSchema` instead. */
  export const inboundSchema = TagManagementRequest$inboundSchema;
  /** @deprecated use `TagManagementRequest$outboundSchema` instead. */
  export const outboundSchema = TagManagementRequest$outboundSchema;
  /** @deprecated use `TagManagementRequest$Outbound` instead. */
  export type Outbound = TagManagementRequest$Outbound;
}

export function tagManagementRequestToJSON(
  tagManagementRequest: TagManagementRequest,
): string {
  return JSON.stringify(
    TagManagementRequest$outboundSchema.parse(tagManagementRequest),
  );
}

export function tagManagementRequestFromJSON(
  jsonString: string,
): SafeParseResult<TagManagementRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TagManagementRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TagManagementRequest' from JSON`,
  );
}
