/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateMembershipRequest = {
  status: string;
};

/** @internal */
export const UpdateMembershipRequest$inboundSchema: z.ZodType<
  UpdateMembershipRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
});

/** @internal */
export type UpdateMembershipRequest$Outbound = {
  status: string;
};

/** @internal */
export const UpdateMembershipRequest$outboundSchema: z.ZodType<
  UpdateMembershipRequest$Outbound,
  z.ZodTypeDef,
  UpdateMembershipRequest
> = z.object({
  status: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateMembershipRequest$ {
  /** @deprecated use `UpdateMembershipRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateMembershipRequest$inboundSchema;
  /** @deprecated use `UpdateMembershipRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateMembershipRequest$outboundSchema;
  /** @deprecated use `UpdateMembershipRequest$Outbound` instead. */
  export type Outbound = UpdateMembershipRequest$Outbound;
}

export function updateMembershipRequestToJSON(
  updateMembershipRequest: UpdateMembershipRequest,
): string {
  return JSON.stringify(
    UpdateMembershipRequest$outboundSchema.parse(updateMembershipRequest),
  );
}

export function updateMembershipRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateMembershipRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateMembershipRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateMembershipRequest' from JSON`,
  );
}
