/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateSurveyRequest = {
  comment?: string | null | undefined;
  score?: number | null | undefined;
};

/** @internal */
export const UpdateSurveyRequest$inboundSchema: z.ZodType<
  UpdateSurveyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  comment: z.nullable(z.string()).optional(),
  score: z.nullable(z.number().int()).optional(),
});

/** @internal */
export type UpdateSurveyRequest$Outbound = {
  comment?: string | null | undefined;
  score?: number | null | undefined;
};

/** @internal */
export const UpdateSurveyRequest$outboundSchema: z.ZodType<
  UpdateSurveyRequest$Outbound,
  z.ZodTypeDef,
  UpdateSurveyRequest
> = z.object({
  comment: z.nullable(z.string()).optional(),
  score: z.nullable(z.number().int()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateSurveyRequest$ {
  /** @deprecated use `UpdateSurveyRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateSurveyRequest$inboundSchema;
  /** @deprecated use `UpdateSurveyRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateSurveyRequest$outboundSchema;
  /** @deprecated use `UpdateSurveyRequest$Outbound` instead. */
  export type Outbound = UpdateSurveyRequest$Outbound;
}

export function updateSurveyRequestToJSON(
  updateSurveyRequest: UpdateSurveyRequest,
): string {
  return JSON.stringify(
    UpdateSurveyRequest$outboundSchema.parse(updateSurveyRequest),
  );
}

export function updateSurveyRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSurveyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSurveyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSurveyRequest' from JSON`,
  );
}
