/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateRoleRequest = {
  color?: string | null | undefined;
  name?: string | null | undefined;
  permissions?: number | null | undefined;
  position?: number | null | undefined;
};

/** @internal */
export const UpdateRoleRequest$inboundSchema: z.ZodType<
  UpdateRoleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  color: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  permissions: z.nullable(z.number().int()).optional(),
  position: z.nullable(z.number().int()).optional(),
});

/** @internal */
export type UpdateRoleRequest$Outbound = {
  color?: string | null | undefined;
  name?: string | null | undefined;
  permissions?: number | null | undefined;
  position?: number | null | undefined;
};

/** @internal */
export const UpdateRoleRequest$outboundSchema: z.ZodType<
  UpdateRoleRequest$Outbound,
  z.ZodTypeDef,
  UpdateRoleRequest
> = z.object({
  color: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  permissions: z.nullable(z.number().int()).optional(),
  position: z.nullable(z.number().int()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateRoleRequest$ {
  /** @deprecated use `UpdateRoleRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateRoleRequest$inboundSchema;
  /** @deprecated use `UpdateRoleRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateRoleRequest$outboundSchema;
  /** @deprecated use `UpdateRoleRequest$Outbound` instead. */
  export type Outbound = UpdateRoleRequest$Outbound;
}

export function updateRoleRequestToJSON(
  updateRoleRequest: UpdateRoleRequest,
): string {
  return JSON.stringify(
    UpdateRoleRequest$outboundSchema.parse(updateRoleRequest),
  );
}

export function updateRoleRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateRoleRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateRoleRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateRoleRequest' from JSON`,
  );
}
