/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateTicketRequest = {
  assignedTo?: string | null | undefined;
  description?: string | null | undefined;
  priority?: string | null | undefined;
  status?: string | null | undefined;
  subject?: string | null | undefined;
};

/** @internal */
export const UpdateTicketRequest$inboundSchema: z.ZodType<
  UpdateTicketRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  assigned_to: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  priority: z.nullable(z.string()).optional(),
  status: z.nullable(z.string()).optional(),
  subject: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "assigned_to": "assignedTo",
  });
});

/** @internal */
export type UpdateTicketRequest$Outbound = {
  assigned_to?: string | null | undefined;
  description?: string | null | undefined;
  priority?: string | null | undefined;
  status?: string | null | undefined;
  subject?: string | null | undefined;
};

/** @internal */
export const UpdateTicketRequest$outboundSchema: z.ZodType<
  UpdateTicketRequest$Outbound,
  z.ZodTypeDef,
  UpdateTicketRequest
> = z.object({
  assignedTo: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  priority: z.nullable(z.string()).optional(),
  status: z.nullable(z.string()).optional(),
  subject: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    assignedTo: "assigned_to",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTicketRequest$ {
  /** @deprecated use `UpdateTicketRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateTicketRequest$inboundSchema;
  /** @deprecated use `UpdateTicketRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateTicketRequest$outboundSchema;
  /** @deprecated use `UpdateTicketRequest$Outbound` instead. */
  export type Outbound = UpdateTicketRequest$Outbound;
}

export function updateTicketRequestToJSON(
  updateTicketRequest: UpdateTicketRequest,
): string {
  return JSON.stringify(
    UpdateTicketRequest$outboundSchema.parse(updateTicketRequest),
  );
}

export function updateTicketRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTicketRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTicketRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTicketRequest' from JSON`,
  );
}
