/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateProfileRequest = {
  email?: string | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const UpdateProfileRequest$inboundSchema: z.ZodType<
  UpdateProfileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
});

/** @internal */
export type UpdateProfileRequest$Outbound = {
  email?: string | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const UpdateProfileRequest$outboundSchema: z.ZodType<
  UpdateProfileRequest$Outbound,
  z.ZodTypeDef,
  UpdateProfileRequest
> = z.object({
  email: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateProfileRequest$ {
  /** @deprecated use `UpdateProfileRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateProfileRequest$inboundSchema;
  /** @deprecated use `UpdateProfileRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateProfileRequest$outboundSchema;
  /** @deprecated use `UpdateProfileRequest$Outbound` instead. */
  export type Outbound = UpdateProfileRequest$Outbound;
}

export function updateProfileRequestToJSON(
  updateProfileRequest: UpdateProfileRequest,
): string {
  return JSON.stringify(
    UpdateProfileRequest$outboundSchema.parse(updateProfileRequest),
  );
}

export function updateProfileRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProfileRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProfileRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProfileRequest' from JSON`,
  );
}
